name: str()
version: str()
appVersion: any(str(), num(), required=True)
description: str()
keywords: list(str(), required=True)
sources: list(str(), required=False)
maintainers: list(include('maintainer'), required=True)
icon: str(required=False)
engine: str(required=False)
condition: str(required=False)
tags: str(required=False)
deprecated: bool(required=False)
kubeVersion: str(required=False)
annotations: map(str(), str(), required=False)
---
maintainer:
  name: str()
  email: str(required=True)
  url: str(required=False)